version: "3.9"

services:
  db:
    image: "postgres:13"
    restart: always
    environment:
      - POSTGRES_USER=jrudio
      - POSTGRES_PASSWORD=xyz123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
